name: Release
on:
    push:
        branches:
            - main
        tags:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Create npmrc
              run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN  }}' >> ${{ github.workspace }}/.npmrc
            - name: Install Deps
              run: npm ci
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Build Game
              run: npm run build
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.0
              with:
                  branch: gh-pages
                  folder: dist